# Generated by Django 5.2.6 on 2025-09-11 12:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('free', 'Free'), ('pro', 'Pro'), ('premium', 'Premium')], max_length=20, unique=True)),
                ('monthly_credits', models.IntegerField(default=75)),
                ('credit_per_clip', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='UserCredits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('used_credits', models.IntegerField(default=0)),
                ('last_reset', models.DateField(auto_now_add=True)),
                ('plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.plan')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VideoRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('original_language', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('total_clips', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('done', 'Done'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Clip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.FloatField()),
                ('end_time', models.FloatField()),
                ('duration', models.FloatField()),
                ('caption_style', models.JSONField(default=dict)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('file_path', models.FileField(blank=True, null=True, upload_to='clips/')),
                ('format', models.CharField(default='mp4', max_length=10)),
                ('video_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clips', to='core.videorequest')),
            ],
        ),
        migrations.CreateModel(
            name='CaptionSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('style', models.CharField(default='default', max_length=50)),
                ('intro_title', models.CharField(blank=True, max_length=100)),
                ('font_size', models.IntegerField(default=24)),
                ('font_color', models.CharField(default='white', max_length=20)),
                ('animation_style', models.CharField(blank=True, max_length=50)),
                ('animation_target', models.CharField(blank=True, max_length=50)),
                ('per_word', models.BooleanField(default=False)),
                ('hide_punctuation', models.BooleanField(default=False)),
                ('ai_highlight_keywords', models.BooleanField(default=False)),
                ('rotate_captions', models.BooleanField(default=False)),
                ('video_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.videorequest')),
            ],
        ),
    ]
