# Generated by Django 5.0.2 on 2025-09-13 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_plan_usercredits_videorequest_clip_captionsettings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clip',
            options={'ordering': ['start_time']},
        ),
        migrations.AddField(
            model_name='clip',
            name='compression_level',
            field=models.CharField(default='balanced', max_length=15),
        ),
        migrations.AddField(
            model_name='clip',
            name='detection_method',
            field=models.CharField(choices=[('ai_detected', 'AI Detected'), ('audio_detected', 'Audio Detected'), ('fixed_interval', 'Fixed Interval')], default='fixed_interval', max_length=20),
        ),
        migrations.AddField(
            model_name='clip',
            name='engagement_score',
            field=models.FloatField(default=5.0),
        ),
        migrations.AddField(
            model_name='clip',
            name='file_size_mb',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clip',
            name='has_word_highlighting',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='clip',
            name='moment_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='clip',
            name='moment_tags',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='clip',
            name='used_caption_style',
            field=models.CharField(default='modern_purple', max_length=20),
        ),
        migrations.AddField(
            model_name='clip',
            name='video_quality',
            field=models.CharField(default='720p', max_length=10),
        ),
        migrations.AddField(
            model_name='videorequest',
            name='caption_style',
            field=models.CharField(choices=[('modern_purple', 'Modern Purple'), ('tiktok_style', 'TikTok Style'), ('youtube_style', 'YouTube Style'), ('instagram_story', 'Instagram Story'), ('podcast_style', 'Podcast Style')], default='modern_purple', max_length=20),
        ),
        migrations.AddField(
            model_name='videorequest',
            name='clip_duration',
            field=models.FloatField(default=30.0),
        ),
        migrations.AddField(
            model_name='videorequest',
            name='compression_level',
            field=models.CharField(choices=[('high_quality', 'High Quality'), ('balanced', 'Balanced'), ('compressed', 'Compressed')], default='balanced', max_length=15),
        ),
        migrations.AddField(
            model_name='videorequest',
            name='enable_word_highlighting',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='videorequest',
            name='estimated_processing_time',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='videorequest',
            name='max_clips',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='videorequest',
            name='moment_detection_type',
            field=models.CharField(choices=[('ai_powered', 'AI Powered'), ('fixed_intervals', 'Fixed Intervals')], default='ai_powered', max_length=20),
        ),
        migrations.AddField(
            model_name='videorequest',
            name='processing_settings',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='videorequest',
            name='video_quality',
            field=models.CharField(choices=[('480p', '480p'), ('720p', '720p'), ('1080p', '1080p'), ('1440p', '1440p'), ('2160p', '2160p')], default='720p', max_length=10),
        ),
    ]
