# Generated by Django 5.0.2 on 2025-09-14 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_paymenthistory_creditpurchase_stripecustomer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='videorequest',
            name='custom_height',
            field=models.IntegerField(blank=True, help_text='Custom height in pixels', null=True),
        ),
        migrations.AddField(
            model_name='videorequest',
            name='custom_width',
            field=models.IntegerField(blank=True, help_text='Custom width in pixels', null=True),
        ),
        migrations.AddField(
            model_name='videorequest',
            name='output_format',
            field=models.CharField(choices=[('horizontal', 'Horizontal (16:9)'), ('vertical', 'Vertical (9:16)'), ('square', 'Square (1:1)'), ('custom', 'Custom Aspect Ratio')], default='horizontal', max_length=20),
        ),
        migrations.AddField(
            model_name='videorequest',
            name='social_platform',
            field=models.CharField(choices=[('youtube', 'YouTube'), ('tiktok', 'TikTok'), ('instagram_story', 'Instagram Story'), ('instagram_post', 'Instagram Post'), ('instagram_reel', 'Instagram Reel'), ('facebook_post', 'Facebook Post'), ('twitter', 'Twitter/X'), ('linkedin', 'LinkedIn'), ('custom', 'Custom')], default='youtube', max_length=20),
        ),
    ]
