# Generated by Django 5.0.2 on 2025-09-14 15:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_videorequest_custom_height_videorequest_custom_width_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QueueStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('total_queued', models.IntegerField(default=0)),
                ('total_processed', models.IntegerField(default=0)),
                ('total_failed', models.IntegerField(default=0)),
                ('avg_wait_time', models.FloatField(default=0.0, help_text='Average wait time in minutes')),
                ('avg_processing_time', models.FloatField(default=0.0, help_text='Average processing time in minutes')),
                ('max_queue_length', models.IntegerField(default=0)),
                ('free_users_processed', models.IntegerField(default=0)),
                ('pro_users_processed', models.IntegerField(default=0)),
                ('premium_users_processed', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='ProcessingQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.IntegerField(choices=[(1, 'Low Priority (Free Users)'), (2, 'Normal Priority (Pro Users)'), (3, 'High Priority (Premium Users)'), (4, 'Critical Priority (Admin/Support)')], default=1)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='queued', max_length=20)),
                ('queued_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('estimated_duration', models.FloatField(blank=True, help_text='Estimated processing time in minutes', null=True)),
                ('actual_duration', models.FloatField(blank=True, help_text='Actual processing time in minutes', null=True)),
                ('worker_id', models.CharField(blank=True, help_text='ID of the worker processing this task', max_length=100)),
                ('error_message', models.TextField(blank=True)),
                ('retry_count', models.IntegerField(default=0)),
                ('max_retries', models.IntegerField(default=3)),
                ('processing_settings', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('video_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='queue_entry', to='core.videorequest')),
            ],
            options={
                'ordering': ['-priority', 'queued_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('processing_started', 'Processing Started'), ('processing_completed', 'Processing Completed'), ('processing_failed', 'Processing Failed'), ('queue_delayed', 'Queue Delayed')], max_length=20)),
                ('notification_type', models.CharField(choices=[('email', 'Email'), ('webhook', 'Webhook'), ('sms', 'SMS')], default='email', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='pending', max_length=10)),
                ('subject', models.CharField(blank=True, max_length=200)),
                ('message', models.TextField(blank=True)),
                ('recipient', models.CharField(max_length=255)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('queue_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='core.processingqueue')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='processingqueue',
            index=models.Index(fields=['status', 'priority', 'queued_at'], name='core_proces_status_167280_idx'),
        ),
        migrations.AddIndex(
            model_name='processingqueue',
            index=models.Index(fields=['user', 'status'], name='core_proces_user_id_1fcc9c_idx'),
        ),
    ]
