# Generated by Django 5.0.2 on 2025-09-15 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_queuestats_processingqueue_notificationevent_and_more'),
        ('social_media', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clip',
            name='auto_post_status',
            field=models.CharField(choices=[('not_scheduled', 'Not Scheduled'), ('scheduled', 'Scheduled'), ('posted', 'Posted'), ('failed', 'Failed')], default='not_scheduled', max_length=20),
        ),
        migrations.AddField(
            model_name='clip',
            name='social_post_ids',
            field=models.JSONField(blank=True, default=list, help_text='IDs of scheduled social media posts'),
        ),
        migrations.AddField(
            model_name='clip',
            name='social_posts_created',
            field=models.BooleanField(default=False, help_text='Whether social media posts were created for this clip'),
        ),
        migrations.AddField(
            model_name='videorequest',
            name='auto_post_to_social',
            field=models.BooleanField(default=False, help_text='Automatically post clips to social media'),
        ),
        migrations.AddField(
            model_name='videorequest',
            name='post_caption_template',
            field=models.TextField(blank=True, help_text='Template for social media captions. Use {title}, {duration}, etc.'),
        ),
        migrations.AddField(
            model_name='videorequest',
            name='post_hashtags',
            field=models.JSONField(blank=True, default=list, help_text='Default hashtags for social media posts'),
        ),
        migrations.AddField(
            model_name='videorequest',
            name='post_schedule_interval',
            field=models.IntegerField(default=60, help_text='Minutes between scheduled posts when posting multiple clips'),
        ),
        migrations.AddField(
            model_name='videorequest',
            name='schedule_posts',
            field=models.BooleanField(default=False, help_text='Schedule posts instead of immediate publishing'),
        ),
        migrations.AddField(
            model_name='videorequest',
            name='social_accounts',
            field=models.ManyToManyField(blank=True, help_text='Social media accounts to post clips to', to='social_media.socialaccount'),
        ),
    ]
