# Generated by Django 5.0.2 on 2025-09-18 14:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_clip_auto_post_status_clip_social_post_ids_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='videorequest',
            name='enable_audio_ducking',
            field=models.BooleanField(default=True, help_text='Lower background music volume when speaker is talking'),
        ),
        migrations.AddField(
            model_name='videorequest',
            name='music_fade_in',
            field=models.FloatField(default=2.0, help_text='Fade in duration for background music (seconds)'),
        ),
        migrations.AddField(
            model_name='videorequest',
            name='music_fade_out',
            field=models.FloatField(default=2.0, help_text='Fade out duration for background music (seconds)'),
        ),
        migrations.AddField(
            model_name='videorequest',
            name='music_volume',
            field=models.FloatField(default=0.3, help_text='Background music volume (0.0-1.0)'),
        ),
        migrations.AddField(
            model_name='videorequest',
            name='original_audio_volume',
            field=models.FloatField(default=1.0, help_text='Original video audio volume (0.0-1.0)'),
        ),
        migrations.CreateModel(
            name='BackgroundMusic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to='background_music/')),
                ('category', models.CharField(choices=[('upbeat', 'Upbeat/Energetic'), ('chill', 'Chill/Relaxing'), ('corporate', 'Corporate/Professional'), ('gaming', 'Gaming/Electronic'), ('cinematic', 'Cinematic/Epic'), ('acoustic', 'Acoustic/Folk'), ('hip_hop', 'Hip Hop/Rap'), ('custom', 'User Upload')], max_length=20)),
                ('duration_seconds', models.FloatField(help_text='Duration in seconds')),
                ('is_preset', models.BooleanField(default=False, help_text='Is this a preset track or user upload?')),
                ('bpm', models.IntegerField(blank=True, help_text='Beats per minute', null=True)),
                ('volume_level', models.FloatField(default=0.3, help_text='Default volume level (0.0-1.0)')),
                ('artist', models.CharField(blank=True, max_length=200)),
                ('license_info', models.TextField(blank=True, help_text='Copyright/license information')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
        migrations.AddField(
            model_name='videorequest',
            name='background_music',
            field=models.ForeignKey(blank=True, help_text='Selected background music track', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.backgroundmusic'),
        ),
    ]
