# Generated by Django 5.0.2 on 2025-09-20 13:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0011_videorequest_preserve_original_timing_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('template_type', models.CharField(choices=[('blog_post', 'Blog Post'), ('show_notes', 'Show Notes'), ('social_media', 'Social Media Post'), ('video_description', 'Video Description'), ('email_newsletter', 'Email Newsletter'), ('transcript', 'Transcript'), ('summary', 'Summary'), ('key_takeaways', 'Key Takeaways'), ('seo_article', 'SEO Article'), ('course_outline', 'Course Outline')], max_length=20)),
                ('platform', models.CharField(choices=[('general', 'General'), ('youtube', 'YouTube'), ('tiktok', 'TikTok'), ('instagram', 'Instagram'), ('twitter', 'Twitter/X'), ('linkedin', 'LinkedIn'), ('facebook', 'Facebook'), ('wordpress', 'WordPress'), ('medium', 'Medium'), ('substack', 'Substack')], default='general', max_length=20)),
                ('prompt_template', models.TextField(help_text='AI prompt template with placeholders')),
                ('output_structure', models.JSONField(default=dict, help_text='Expected output structure')),
                ('max_words', models.IntegerField(default=1000, help_text='Maximum word count')),
                ('min_words', models.IntegerField(default=100, help_text='Minimum word count')),
                ('tone', models.CharField(default='professional', max_length=50)),
                ('style', models.CharField(default='informative', max_length=50)),
                ('include_seo_meta', models.BooleanField(default=False)),
                ('target_keywords', models.JSONField(blank=True, default=list)),
                ('include_headings', models.BooleanField(default=True)),
                ('include_bullet_points', models.BooleanField(default=True)),
                ('is_built_in', models.BooleanField(default=True, help_text='Built-in system template')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['template_type', 'name'],
                'unique_together': {('name', 'template_type', 'platform')},
            },
        ),
        migrations.CreateModel(
            name='ContentGenerationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_instructions', models.TextField(blank=True, help_text='Additional user instructions')),
                ('target_audience', models.CharField(blank=True, max_length=200)),
                ('brand_voice', models.CharField(blank=True, max_length=100)),
                ('custom_keywords', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('priority', models.IntegerField(choices=[(1, 'Low'), (2, 'Normal'), (3, 'High'), (4, 'Urgent')], default=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('processing_time_seconds', models.FloatField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('retry_count', models.IntegerField(default=0)),
                ('max_retries', models.IntegerField(default=3)),
                ('ai_model_used', models.CharField(blank=True, max_length=50)),
                ('tokens_used', models.IntegerField(default=0)),
                ('cost_estimate', models.DecimalField(decimal_places=4, default=0.0, max_digits=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('video_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_requests', to='core.videorequest')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content_generation.contenttemplate')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GeneratedContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=500)),
                ('content', models.TextField()),
                ('format', models.CharField(choices=[('markdown', 'Markdown'), ('html', 'HTML'), ('plain_text', 'Plain Text'), ('json', 'JSON')], default='markdown', max_length=20)),
                ('meta_title', models.CharField(blank=True, max_length=200)),
                ('meta_description', models.CharField(blank=True, max_length=300)),
                ('keywords', models.JSONField(blank=True, default=list)),
                ('headings', models.JSONField(blank=True, default=list)),
                ('hashtags', models.JSONField(blank=True, default=list)),
                ('mentions', models.JSONField(blank=True, default=list)),
                ('call_to_action', models.CharField(blank=True, max_length=200)),
                ('word_count', models.IntegerField(default=0)),
                ('reading_time_minutes', models.FloatField(default=0.0)),
                ('readability_score', models.FloatField(blank=True, null=True)),
                ('ai_confidence_score', models.FloatField(default=0.0, help_text='AI confidence in content quality (0-1)')),
                ('user_rating', models.IntegerField(blank=True, help_text='User rating 1-5', null=True)),
                ('version', models.IntegerField(default=1)),
                ('is_latest', models.BooleanField(default=True)),
                ('is_published', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('published_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='generated_content', to='content_generation.contentgenerationrequest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PublishingIntegration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('wordpress', 'WordPress'), ('medium', 'Medium'), ('substack', 'Substack'), ('linkedin', 'LinkedIn'), ('twitter', 'Twitter/X'), ('facebook', 'Facebook'), ('custom_webhook', 'Custom Webhook')], max_length=20)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('publishing', 'Publishing'), ('published', 'Published'), ('failed', 'Failed')], default='scheduled', max_length=20)),
                ('scheduled_for', models.DateTimeField(blank=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('published_url', models.URLField(blank=True)),
                ('platform_post_id', models.CharField(blank=True, max_length=100)),
                ('platform_settings', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('analytics_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('generated_content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publications', to='content_generation.generatedcontent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContentGenerationUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tokens_consumed', models.IntegerField(default=0)),
                ('processing_time_seconds', models.FloatField(default=0.0)),
                ('cost_usd', models.DecimalField(decimal_places=4, default=0.0, max_digits=10)),
                ('plan_type', models.CharField(default='free', max_length=20)),
                ('credits_used', models.IntegerField(default=1)),
                ('ai_model', models.CharField(default='gpt-3.5-turbo', max_length=50)),
                ('template_type', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content_generation.contentgenerationrequest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='content_gen_user_id_a3d20a_idx'), models.Index(fields=['plan_type', 'created_at'], name='content_gen_plan_ty_4409e4_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='contentgenerationrequest',
            index=models.Index(fields=['user', 'status'], name='content_gen_user_id_982c6a_idx'),
        ),
        migrations.AddIndex(
            model_name='contentgenerationrequest',
            index=models.Index(fields=['status', 'priority', 'created_at'], name='content_gen_status_32f2da_idx'),
        ),
        migrations.AddIndex(
            model_name='generatedcontent',
            index=models.Index(fields=['user', 'is_published'], name='content_gen_user_id_8c38a9_idx'),
        ),
        migrations.AddIndex(
            model_name='generatedcontent',
            index=models.Index(fields=['content_request', 'version'], name='content_gen_content_88fd5a_idx'),
        ),
        migrations.AddIndex(
            model_name='publishingintegration',
            index=models.Index(fields=['user', 'platform', 'status'], name='content_gen_user_id_c9d6c6_idx'),
        ),
        migrations.AddIndex(
            model_name='publishingintegration',
            index=models.Index(fields=['scheduled_for'], name='content_gen_schedul_485cb4_idx'),
        ),
    ]
